export interface StressEntry {
  major: string
  lowestStressWeek: number
  beginStressWeek: number
  highestStressWeek: number
  questionType: "lowest" | "begin" | "highest"
}

export const stressData: StressEntry[] = [
  // Ciencia de la Computación - 32 entries
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 2,
    highestStressWeek: 2,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 2,
    highestStressWeek: 2,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 2,
    highestStressWeek: 2,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 11,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 11,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 11,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 8,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 8,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 8,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 6,
    beginStressWeek: 6,
    highestStressWeek: 9,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 6,
    beginStressWeek: 6,
    highestStressWeek: 9,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 6,
    beginStressWeek: 6,
    highestStressWeek: 9,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 5,
    highestStressWeek: 6,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 5,
    highestStressWeek: 6,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 9,
    beginStressWeek: 5,
    highestStressWeek: 6,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 3,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 3,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ciencia de la Computación",
    lowestStressWeek: 3,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "highest",
  },

  // Ciencia de Datos - 19 entries
  { major: "Ciencia de Datos", lowestStressWeek: 3, beginStressWeek: 1, highestStressWeek: 9, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 3, beginStressWeek: 1, highestStressWeek: 9, questionType: "begin" },
  { major: "Ciencia de Datos", lowestStressWeek: 3, beginStressWeek: 1, highestStressWeek: 9, questionType: "highest" },
  { major: "Ciencia de Datos", lowestStressWeek: 9, beginStressWeek: 8, highestStressWeek: 9, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 9, beginStressWeek: 8, highestStressWeek: 9, questionType: "begin" },
  { major: "Ciencia de Datos", lowestStressWeek: 9, beginStressWeek: 8, highestStressWeek: 9, questionType: "highest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 10, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 10, questionType: "begin" },
  {
    major: "Ciencia de Datos",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 10,
    questionType: "highest",
  },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 6, highestStressWeek: 7, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 6, highestStressWeek: 7, questionType: "begin" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 6, highestStressWeek: 7, questionType: "highest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 13, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 13, questionType: "begin" },
  {
    major: "Ciencia de Datos",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "highest",
  },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 6, highestStressWeek: 10, questionType: "lowest" },
  { major: "Ciencia de Datos", lowestStressWeek: 1, beginStressWeek: 6, highestStressWeek: 10, questionType: "begin" },
  {
    major: "Ciencia de Datos",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "highest",
  },

  // Ingeniería Electrónica
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 2,
    beginStressWeek: 12,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 2,
    beginStressWeek: 12,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 2,
    beginStressWeek: 12,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 5,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 5,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 5,
    beginStressWeek: 8,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 13,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 13,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Electrónica",
    lowestStressWeek: 13,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },

  // Sistemas de Información
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 9,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 9,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 9,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Sistemas de Información",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 15,
    questionType: "highest",
  },

  // Ingeniería Industrial
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 10,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 10,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 10,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 10,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 10,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 10,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 9,
    beginStressWeek: 7,
    highestStressWeek: 7,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 3,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 9,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 9,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 1,
    beginStressWeek: 9,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Industrial",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "highest",
  },

  // Ingeniería Mecánica
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 12,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 12,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 12,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecánica",
    lowestStressWeek: 5,
    beginStressWeek: 13,
    highestStressWeek: 16,
    questionType: "highest",
  },

  // Bioingeniería
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 12, questionType: "lowest" },
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 12, questionType: "begin" },
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 8, highestStressWeek: 12, questionType: "highest" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 2, highestStressWeek: 7, questionType: "lowest" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 2, highestStressWeek: 7, questionType: "begin" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 2, highestStressWeek: 7, questionType: "highest" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 13, highestStressWeek: 14, questionType: "lowest" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 13, highestStressWeek: 14, questionType: "begin" },
  { major: "Bioingeniería", lowestStressWeek: 9, beginStressWeek: 13, highestStressWeek: 14, questionType: "highest" },
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 7, highestStressWeek: 8, questionType: "lowest" },
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 7, highestStressWeek: 8, questionType: "begin" },
  { major: "Bioingeniería", lowestStressWeek: 1, beginStressWeek: 7, highestStressWeek: 8, questionType: "highest" },

  // Ingeniería Ambiental
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 7,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 7,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 7,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 9,
    beginStressWeek: 8,
    highestStressWeek: 9,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 9,
    beginStressWeek: 8,
    highestStressWeek: 9,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 9,
    beginStressWeek: 8,
    highestStressWeek: 9,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 5,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 5,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Ambiental",
    lowestStressWeek: 5,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },

  // Ingeniería CIvil
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 1,
    beginStressWeek: 10,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  { major: "Ingeniería CIvil", lowestStressWeek: 1, beginStressWeek: 10, highestStressWeek: 10, questionType: "begin" },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 1,
    beginStressWeek: 10,
    highestStressWeek: 10,
    questionType: "highest",
  },
  { major: "Ingeniería CIvil", lowestStressWeek: 4, beginStressWeek: 9, highestStressWeek: 14, questionType: "lowest" },
  { major: "Ingeniería CIvil", lowestStressWeek: 4, beginStressWeek: 9, highestStressWeek: 14, questionType: "begin" },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 4,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "highest",
  },
  { major: "Ingeniería CIvil", lowestStressWeek: 3, beginStressWeek: 7, highestStressWeek: 8, questionType: "lowest" },
  { major: "Ingeniería CIvil", lowestStressWeek: 3, beginStressWeek: 7, highestStressWeek: 8, questionType: "begin" },
  { major: "Ingeniería CIvil", lowestStressWeek: 3, beginStressWeek: 7, highestStressWeek: 8, questionType: "highest" },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 3,
    beginStressWeek: 11,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  { major: "Ingeniería CIvil", lowestStressWeek: 3, beginStressWeek: 11, highestStressWeek: 16, questionType: "begin" },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 3,
    beginStressWeek: 11,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 14,
    beginStressWeek: 15,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 14,
    beginStressWeek: 15,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 14,
    beginStressWeek: 15,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 13,
    beginStressWeek: 7,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  { major: "Ingeniería CIvil", lowestStressWeek: 13, beginStressWeek: 7, highestStressWeek: 16, questionType: "begin" },
  {
    major: "Ingeniería CIvil",
    lowestStressWeek: 13,
    beginStressWeek: 7,
    highestStressWeek: 16,
    questionType: "highest",
  },

  // Ingeniería Mecatrónica
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 3,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 10,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 10,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 8,
    highestStressWeek: 10,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 1,
    beginStressWeek: 5,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 6,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 6,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 6,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería Mecatrónica",
    lowestStressWeek: 3,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "highest",
  },

  // Administración & Negocios Sostenibles
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 8,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 5,
    beginStressWeek: 10,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 5,
    beginStressWeek: 10,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Sostenibles",
    lowestStressWeek: 5,
    beginStressWeek: 10,
    highestStressWeek: 13,
    questionType: "highest",
  },

  // Administración & Negocios Digitales
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 4,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 4,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 4,
    beginStressWeek: 9,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 1,
    beginStressWeek: 7,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 12,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 12,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 10,
    highestStressWeek: 12,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 2,
    beginStressWeek: 5,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Administración & Negocios Digitales",
    lowestStressWeek: 5,
    beginStressWeek: 14,
    highestStressWeek: 16,
    questionType: "highest",
  },

  // Business Analytics
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 12,
    questionType: "lowest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 12,
    questionType: "begin",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 2,
    beginStressWeek: 9,
    highestStressWeek: 12,
    questionType: "highest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "lowest",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "begin",
  },
  {
    major: "Business Analytics",
    lowestStressWeek: 4,
    beginStressWeek: 7,
    highestStressWeek: 12,
    questionType: "highest",
  },

  // Ciberseguridad
  { major: "Ciberseguridad", lowestStressWeek: 3, beginStressWeek: 10, highestStressWeek: 15, questionType: "lowest" },
  { major: "Ciberseguridad", lowestStressWeek: 3, beginStressWeek: 10, highestStressWeek: 15, questionType: "begin" },
  { major: "Ciberseguridad", lowestStressWeek: 3, beginStressWeek: 10, highestStressWeek: 15, questionType: "highest" },
  { major: "Ciberseguridad", lowestStressWeek: 5, beginStressWeek: 9, highestStressWeek: 15, questionType: "lowest" },
  { major: "Ciberseguridad", lowestStressWeek: 5, beginStressWeek: 9, highestStressWeek: 15, questionType: "begin" },
  { major: "Ciberseguridad", lowestStressWeek: 5, beginStressWeek: 9, highestStressWeek: 15, questionType: "highest" },
  { major: "Ciberseguridad", lowestStressWeek: 2, beginStressWeek: 7, highestStressWeek: 13, questionType: "lowest" },
  { major: "Ciberseguridad", lowestStressWeek: 2, beginStressWeek: 7, highestStressWeek: 13, questionType: "begin" },
  { major: "Ciberseguridad", lowestStressWeek: 2, beginStressWeek: 7, highestStressWeek: 13, questionType: "highest" },

  // Ingeniería de la Energía
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 1,
    beginStressWeek: 4,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 2,
    beginStressWeek: 7,
    highestStressWeek: 13,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 15,
    beginStressWeek: 7,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 15,
    beginStressWeek: 7,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 15,
    beginStressWeek: 7,
    highestStressWeek: 14,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 6,
    highestStressWeek: 8,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 8,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 9,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 9,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 16,
    beginStressWeek: 4,
    highestStressWeek: 9,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 4,
    beginStressWeek: 8,
    highestStressWeek: 16,
    questionType: "highest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "lowest",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "begin",
  },
  {
    major: "Ingeniería  de la Energía",
    lowestStressWeek: 6,
    beginStressWeek: 9,
    highestStressWeek: 13,
    questionType: "highest",
  },

  // Ingeniería Química
  {
    major: "Ingeniería Química",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "begin",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 3,
    beginStressWeek: 10,
    highestStressWeek: 15,
    questionType: "highest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 1,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "begin",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 2,
    beginStressWeek: 6,
    highestStressWeek: 11,
    questionType: "highest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "lowest",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "begin",
  },
  {
    major: "Ingeniería Química",
    lowestStressWeek: 5,
    beginStressWeek: 11,
    highestStressWeek: 14,
    questionType: "highest",
  },
]
